version: '3.12'

services:
  web-app:
    build: ./web-app
    ports:
      - "8000:5000"
    environment:
      - MONGO_DBNAME=MoodMapDB
      - MONGO_URI=mongodb://admin:secret@mongodb:27017
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - FLASK_PORT=8000
    env_file:
      - ./web-app/.env
    depends_on:
      - mongodb
      - machine-learning-client
    networks:
      - my_network
  mongodb:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=secret
    image: mongo
    ports:
      - 27017:27017
    networks:
      - my_network
    volumes:
      - mongodb-data:/data/db
  machine-learning-client:
    build: ./machine-learning-client
    ports:
      - "5000:5000"    
    env_file:
      - ./machine-learning-client/.env
    networks:
      - my_network

volumes:
  mongodb-data:

networks:
  my_network:
    driver: bridge

